# Generated by Django 3.0.7 on 2020-06-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20, unique=True, verbose_name='id类型')),
                ('Count', models.PositiveIntegerField(default=0, editable=False, verbose_name='计数')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='用户id')),
                ('UserPwd', models.CharField(max_length=20, verbose_name='密码')),
                ('UserName', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('UserLevel', models.SmallIntegerField(default=1, verbose_name='用户等级')),
                ('UserCurExp', models.SmallIntegerField(default=0, verbose_name='用户当前经验')),
                ('UserMaxExp', models.SmallIntegerField(default=1000, verbose_name='用户最大经验')),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
    ]
