# Generated by Django 3.0.7 on 2020-06-23 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovId', models.CharField(max_length=50, unique=True)),
                ('MovName', models.CharField(max_length=100, verbose_name='电影标题')),
                ('MovType', models.SmallIntegerField(verbose_name='电影类型')),
                ('MovLength', models.TimeField(verbose_name='电影时长')),
                ('MovImg', models.ImageField(upload_to='cover/', verbose_name='电影封面')),
                ('MovOrigin', models.SmallIntegerField(verbose_name='电影产地')),
                ('MovCompany', models.CharField(max_length=100, verbose_name='电影公司')),
                ('MovDirector', models.CharField(max_length=100, verbose_name='电影导演')),
                ('MovDescription', models.TextField(verbose_name='电影描述')),
            ],
            options={
                'verbose_name': '电影信息',
                'verbose_name_plural': '电影信息',
            },
        ),
        migrations.CreateModel(
            name='MovieTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MovTagId', models.CharField(max_length=20, unique=True)),
                ('MovTagCnt', models.CharField(max_length=20, unique=True, verbose_name='标签内容')),
            ],
            options={
                'verbose_name': '电影标签',
                'verbose_name_plural': '电影标签',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(max_length=30, unique=True, verbose_name='用户id')),
                ('UserPsw', models.CharField(max_length=20, verbose_name='密码')),
                ('UserName', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('UserLevel', models.SmallIntegerField(verbose_name='用户等级')),
                ('UserCurExp', models.SmallIntegerField(verbose_name='用户当前经验')),
                ('UserMaxExp', models.SmallIntegerField(verbose_name='用户最大经验')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='ReplyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordId', models.CharField(max_length=100, unique=True, verbose_name='实体id')),
                ('TargetId', models.CharField(max_length=50, verbose_name='目标id')),
                ('RecordTime', models.DateTimeField(auto_now_add=True)),
                ('ReplyType', models.PositiveSmallIntegerField(choices=[(1, '电影'), (2, '评论')], verbose_name='回复类型')),
                ('ReplyGrade', models.SmallIntegerField(blank=True, verbose_name='评分')),
                ('ReplyContent', models.TextField(verbose_name='回复内容')),
                ('AgreeCount', models.PositiveIntegerField(default=0, editable=False, verbose_name='点赞数')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User', to_field='UserId', verbose_name='用户id')),
            ],
            options={
                'abstract': False,
                'index_together': {('UserId', 'TargetId')},
            },
        ),
        migrations.CreateModel(
            name='MovTagConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AgreeCount', models.PositiveIntegerField(default=0, editable=False, verbose_name='点赞数')),
                ('MovId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Movie', to_field='MovId', verbose_name='电影id')),
                ('MovTagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.MovieTag', to_field='MovTagId', verbose_name='标签id')),
            ],
            options={
                'index_together': {('MovTagId', 'MovId')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordId', models.CharField(max_length=100, unique=True, verbose_name='实体id')),
                ('TargetId', models.CharField(max_length=50, verbose_name='目标id')),
                ('RecordTime', models.DateTimeField(auto_now_add=True)),
                ('FavoriteType', models.PositiveSmallIntegerField(choices=[(1, '电影')], default=1, verbose_name='收藏类型')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User', to_field='UserId', verbose_name='用户id')),
            ],
            options={
                'abstract': False,
                'index_together': {('UserId', 'TargetId')},
            },
        ),
        migrations.CreateModel(
            name='EditRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordId', models.CharField(max_length=100, unique=True, verbose_name='实体id')),
                ('TargetId', models.CharField(max_length=50, verbose_name='目标id')),
                ('RecordTime', models.DateTimeField(auto_now_add=True)),
                ('EditType', models.PositiveSmallIntegerField(choices=[(1, '修改信息'), (2, '添加标签')], verbose_name='编辑类型')),
                ('EditContent', models.TextField(verbose_name='修改内容')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User', to_field='UserId', verbose_name='用户id')),
            ],
            options={
                'abstract': False,
                'index_together': {('UserId', 'TargetId')},
            },
        ),
        migrations.CreateModel(
            name='Agree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordId', models.CharField(max_length=100, unique=True, verbose_name='实体id')),
                ('TargetId', models.CharField(max_length=50, verbose_name='目标id')),
                ('RecordTime', models.DateTimeField(auto_now_add=True)),
                ('AgreeType', models.PositiveSmallIntegerField(choices=[(1, '评论'), (2, '标签')], verbose_name='点赞类型')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User', to_field='UserId', verbose_name='用户id')),
            ],
            options={
                'abstract': False,
                'index_together': {('UserId', 'TargetId')},
            },
        ),
    ]
