# Generated by Django 3.0.7 on 2020-06-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MovType',
            field=models.IntegerField(verbose_name='电影类型'),
        ),
    ]
