# Generated by Django 2.1.2 on 2020-07-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='MovLanguage',
        ),
    ]
