# Generated by Django 3.0.7 on 2020-06-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20200623_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editrecord',
            options={'verbose_name': '编辑记录', 'verbose_name_plural': '编辑记录'},
        ),
        migrations.AlterModelOptions(
            name='replyrecord',
            options={'verbose_name': '评论记录', 'verbose_name_plural': '评论记录'},
        ),
        migrations.AlterField(
            model_name='agree',
            name='RecordId',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='实体id'),
        ),
        migrations.AlterField(
            model_name='editrecord',
            name='RecordId',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='实体id'),
        ),
        migrations.AlterField(
            model_name='favoriterecord',
            name='RecordId',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='实体id'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovId',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='movietag',
            name='MovTagId',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='replyrecord',
            name='RecordId',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='实体id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserId',
            field=models.CharField(editable=False, max_length=30, unique=True, verbose_name='用户id'),
        ),
        migrations.AlterIndexTogether(
            name='editrecord',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='replyrecord',
            index_together=set(),
        ),
    ]
