# Generated by Django 3.0.7 on 2020-06-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20200623_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MovImg',
            field=models.ImageField(default='default_cover.bmp', upload_to='cover/', verbose_name='电影封面'),
        ),
    ]
