# Generated by Django 2.1.2 on 2020-07-04 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_movie_movlanguage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actorconnection',
            options={'verbose_name': '参演/导演信息', 'verbose_name_plural': '参演/导演信息'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'managed': True, 'verbose_name': '电影信息', 'verbose_name_plural': '电影信息'},
        ),
        migrations.AlterField(
            model_name='actor',
            name='ActorId',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='演员id'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovDirector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.Actor', to_field='ActorId', verbose_name='导演id'),
        ),
    ]
