# Generated by Django 2.1.2 on 2020-07-04 08:46

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20200704_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MovImg',
            field=models.ImageField(default='static/cover/default_cover.png', upload_to=Main.models.cover_directory_path, verbose_name='电影封面'),
        ),
    ]
