# Generated by Django 3.0.7 on 2020-06-23 08:15

import Main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20200623_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agree',
            name='RecordId',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='实体id'),
        ),
        migrations.AlterField(
            model_name='editrecord',
            name='RecordId',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='实体id'),
        ),
        migrations.AlterField(
            model_name='favoriterecord',
            name='RecordId',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='实体id'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovId',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovImg',
            field=models.ImageField(default='cover/default_cover.bmp', upload_to=Main.models.cover_directory_path, verbose_name='电影封面'),
        ),
        migrations.AlterField(
            model_name='movietag',
            name='MovTagId',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='replyrecord',
            name='RecordId',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='实体id'),
        ),
        migrations.AlterField(
            model_name='replyrecord',
            name='ReplyGrade',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserId',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='用户id'),
        ),
    ]
