# Generated by Django 2.1.2 on 2020-07-05 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20200704_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='MovOriginId',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='原始id'),
            preserve_default=False,
        ),
    ]
