# Generated by Django 3.0.7 on 2020-06-23 09:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20200623_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActorId', models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='演员id')),
                ('ActorName', models.CharField(max_length=50, verbose_name='演员姓名')),
                ('ActorArea', models.CharField(blank=True, max_length=50, null=True, verbose_name='演员地区')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='MovDate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='电影上映时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='MovImdbId',
            field=models.IntegerField(default=0, verbose_name='IMDB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='MovTmdbId',
            field=models.IntegerField(default=0, verbose_name='TMDB'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovOrigin',
            field=models.SmallIntegerField(choices=[(0, '国产'), (1, '欧美'), (2, '日本'), (3, '印度'), (4, '其他')], verbose_name='电影产地'),
        ),
        migrations.AlterUniqueTogether(
            name='movtagconnection',
            unique_together={('MovTagId', 'MovId')},
        ),
        migrations.CreateModel(
            name='ActorConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ActorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Actor', to_field='ActorId', verbose_name='演员id')),
                ('MovId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Movie', to_field='MovId', verbose_name='电影id')),
            ],
            options={
                'unique_together': {('ActorId', 'MovId')},
                'index_together': {('ActorId', 'MovId')},
            },
        ),
    ]
