# Generated by Django 3.0.7 on 2020-06-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20200623_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=20, unique=True, verbose_name='id类型')),
                ('Count', models.PositiveIntegerField(default=0, editable=False, verbose_name='计数')),
            ],
        ),
    ]
