# Generated by Django 2.1.2 on 2020-07-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_movie_movoriginid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CosRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie1', models.CharField(max_length=50, verbose_name='电影1id')),
                ('Movie1Origin', models.CharField(max_length=50, verbose_name='电影1原始id')),
                ('Movie2', models.CharField(max_length=50, verbose_name='电影2id')),
                ('Movie2Origin', models.CharField(max_length=50, verbose_name='电影2原始id')),
                ('Relation', models.FloatField(verbose_name='相关系数')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='Types',
            field=models.IntegerField(default=-1073741825, verbose_name='用户喜欢的类型'),
        ),
        migrations.AlterUniqueTogether(
            name='cosrelation',
            unique_together={('Movie1', 'Movie2')},
        ),
        migrations.AlterIndexTogether(
            name='cosrelation',
            index_together={('Movie1', 'Movie2')},
        ),
    ]
