# Generated by Django 3.0.7 on 2020-06-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_idcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='UserPsw',
            new_name='UserPwd',
        ),
        migrations.AlterField(
            model_name='user',
            name='UserCurExp',
            field=models.SmallIntegerField(default=0, verbose_name='用户当前经验'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserLevel',
            field=models.SmallIntegerField(default=1, verbose_name='用户等级'),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserMaxExp',
            field=models.SmallIntegerField(default=1000, verbose_name='用户最大经验'),
        ),
    ]
