# Generated by Django 3.0.7 on 2020-06-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_idcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='ActorSex',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女'), (3, '未知')], default=3, verbose_name='演员性别'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='ActorArea',
            field=models.CharField(blank=True, default='未知', max_length=50, verbose_name='演员地区'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovCompany',
            field=models.CharField(default='未知', max_length=100, verbose_name='电影公司'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovDate',
            field=models.DateField(default='null', verbose_name='电影上映时间'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovDescription',
            field=models.TextField(default='无', verbose_name='电影描述'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovDirector',
            field=models.CharField(default='未知', max_length=100, verbose_name='电影导演'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovImdbId',
            field=models.IntegerField(default=0, verbose_name='IMDB'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovLength',
            field=models.TimeField(default='None', verbose_name='电影时长'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovOrigin',
            field=models.SmallIntegerField(choices=[(0, '国产'), (1, '欧美'), (2, '日本'), (3, '印度'), (4, '其他')], default=4, verbose_name='电影产地'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovTmdbId',
            field=models.IntegerField(default=0, verbose_name='TMDB'),
        ),
    ]
