# Generated by Django 3.0.7 on 2020-06-24 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20200623_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': '演员信息', 'verbose_name_plural': '演员信息'},
        ),
    ]
