# Generated by Django 3.0.7 on 2020-07-06 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_remove_viewrecord_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MovDirector',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.Actor', to_field='ActorId', verbose_name='导演id'),
        ),
    ]
