# Generated by Django 3.0.7 on 2020-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20200626_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='MovOrigin',
            field=models.SmallIntegerField(default=16, verbose_name='电影产地'),
        ),
    ]
