# Generated by Django 3.0.7 on 2020-06-26 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20200626_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actorconnection',
            options={'verbose_name': '参演信息', 'verbose_name_plural': '参演信息'},
        ),
        migrations.AlterModelOptions(
            name='movtagconnection',
            options={'verbose_name': '标签联系信息', 'verbose_name_plural': '标签联系信息'},
        ),
    ]
