# Generated by Django 3.0.7 on 2020-06-28 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20200626_1707'),
        ('Main', '0008_auto_20200624_0313'),
    ]

    operations = [
    ]
