# Generated by Django 2.1.2 on 2020-07-02 03:03

import Main.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordId', models.CharField(blank=True, editable=False, max_length=100, unique=True, verbose_name='实体id')),
                ('TargetId', models.CharField(max_length=50, verbose_name='目标id')),
                ('RecordTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='HasView',
            field=models.BooleanField(default=False, verbose_name='是否有过浏览记录'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='MovImg',
            field=models.ImageField(default='static/cover/default_cover.bmp', upload_to=Main.models.cover_directory_path, verbose_name='电影封面'),
        ),
        migrations.AddField(
            model_name='viewrecord',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User', to_field='UserId', verbose_name='用户id'),
        ),
        migrations.AlterIndexTogether(
            name='viewrecord',
            index_together={('UserId', 'TargetId')},
        ),
    ]
